### ISSUE TITLE
feat: auto embed character limiting

### ISSUE THREAD

**Issue by Dworv** [interactions-py/enhanced#6]
~~this is more complicated than it looks~~

I propose an optional setting while loading the ext to automatically check and fix if any of the character/field/embed limits are being broken when somebody sends an embed, so that they don't have to make it themselves. It would look something like this:

`bot.load('interactions.ext.enhanced', limit_embeds=True)`

While it seems simple to check if the embeds in a message break the rules, it is actually relatively complicated. You can find information on embed limits from this screenshot: 
![image](https://user-images.githubusercontent.com/88643996/158503765-808c87a9-6e79-4251-b7ee-b7b8b60ccabf.png)

Edit: It would also be cool to mention when an embed breaks the rule in logging, possibly directly in stdout with a separate loading argument

**Comment by Toricane** [comment]
Oh I see
Basically an error with actual description of what is wrong in the embed instead of a 50035 invalid body form or whatever that's called
Could also implement for components and message content, thanks

**Comment by Dworv** [comment]
> Oh I see Basically an error with actual description of what is wrong in the embed instead of a 50035 invalid body form or whatever that's called Could also implement for components and message content, thanks

You may want to check with fl0w on that as he might be planning to use the info provided from Discord in 50035s, I meant more automatically shortening things as needed :)

**Comment by Toricane** [comment]
May include this for v4

**Comment by Toricane** [comment]
@Dworv do you still want this? Cuz the better error handling is implemented

**Comment by Dworv** [comment]
its ok
