### ISSUE TITLE
feat: better subcommand system

### ISSUE THREAD

**Issue by Dworv** [interactions-py/enhanced#8]
at the moment, you implement subcommands using a `base` object. however, this is not exactly idea. it would be prudent to move towards to the more comprehensive `@subcommand` decorator. 

eg
`@bot.subcommand(base="an", group="epic", name="subcommand")`
`async def whatever(ctx):`

or possibly
`@bot.subcommand`
`async def an_epic_subcommand(ctx):`

**Comment by Toricane** [comment]
I was actually thinking about doing this, so yes, I can implement that.

By the way, the reason why the current system is effective is that the `base` and `group` fields are redundant and it made sure you didn't have to specify them over and over again, this is also another reason why I originally did not opt for this design.

**Comment by Toricane** [comment]
```py
@bot.command(name="top-level")
async def top_level_part(ctx):
  ... # this is if people want to run code if the subcommand, regardless of the path, is used.

@top_level_part.subcommand("subcommand_name") # options should be allowed too in theory
async def sub_command_part(ctx):
  ... # this is now the subcommand data for that specific path. 

# okay, but what about groups?

@top_level_part.group("the_group_name", subcommands=["sub1", "sub2"]) # we can let people manually define the subcommand names, which will target *COROUTINE* names here for ease.
async def group_part(ctx):
  ...

# method 1
@group_part.subcommand()
async def sub1(ctx):
  ... # allowing code to be ran for the subcomamnd "sub1" under the subcommand group "the_group_name"

# method 2
@group_part.sub1()
async def custom_name_subcommand_coro(ctx):
  ... # will instead use a custom-created method from the subcommand group constructor, "class.sub1()"
```
Suggested by @goverfl0w

**Comment by goverfl0w** [comment]
For extra clarity, here are the reasons why I've made the suggestion above:

- Users are far more likely to want to use decorators to their fullest instead of declaring `SubcommandBase` objects for every subcommand to extend their decorators off of for subcommands. This design caters towards the laziness of a developer and adds intuitiveness to the actual "structure" of subcommands much like the paradigm gives.
- This allows a bot developer to have multiple coroutines dispatched if they'd like to. Of course, not every decorator is *required* (group for example) but it's present if we want to give power to the developer for additional processes to occur.
- A developer wants to be able to neatly structure how "conditions" appear with subcommands. The core library suggests for you to [take this path, which not all developers may like.](https://github.com/interactions-py/Astro/blob/master/src/exts/tag.py#L18-L36) The suggestion gives the best solution possible to avoiding this by chaining all parts of a "subcommand" by decorator.

**Comment by Dworv** [comment]
> For extra clarity, here are the reasons why I've made the suggestion above:
> 
> * Users are far more likely to want to use decorators to their fullest instead of declaring `SubcommandBase` objects for every subcommand to extend their decorators off of for subcommands. This design caters towards the laziness of a developer and adds intuitiveness to the actual "structure" of subcommands much like the paradigm gives.
> * This allows a bot developer to have multiple coroutines dispatched if they'd like to. Of course, not every decorator is _required_ (group for example) but it's present if we want to give power to the developer for additional processes to occur.
> * A developer wants to be able to neatly structure how "conditions" appear with subcommands. The core library suggests for you to [take this path, which not all developers may like.](https://github.com/interactions-py/Astro/blob/master/src/exts/tag.py#L18-L36) The suggestion gives the best solution possible to avoiding this by chaining all parts of a "subcommand" by decorator.

This isn't entirely ideal though. Discord doesn't allow you to have a regular command (eg. `/base`) that has subcommands at the same time (eg `/base sub`). This means users would have to define placeholder functions to base their subcommands off of, which isn't ideal either.

**Comment by Dworv** [comment]
oh did i not read it correctly? whoops

**Comment by goverfl0w** [comment]
Astro will most likely get its subcommands rewritten with `interactions.ext.enhanced` once this Issue has been closed with a PR appropriately merged and released. Looking forward to seeing how this will be done

**Comment by Toricane** [comment]
However, an issue with this is I won't know when to sync the subcommand.
Might need something like this:
```py
@bot.command(...)
async def base(...): ...

@base.subcommand(...)
async def subcommand(...): ...
...
base.finish()
```
Or, maybe I could overwrite `bot.start()` (or `._ready()` or something similar) and sync it there instead?
That would eliminate the issue.
I could add all the command objects needed to be synced and they will sync when `bot.start()` is called.
Let me know which one you prefer.

**Comment by Toricane** [comment]
I'm not sure if method 2 has a use case other than just a different way of creating subcommands so I won't implement it unless there is a good reason to do so

**Comment by jameswalston** [comment]
Method 2 allows you to avoid restricting your subcommand name by only underscores being allowed as it attaches directly to the coroutine it was registered to, basically

**Comment by Toricane** [comment]
But you still can't use `-` when calling a method, right? What's the point? I don't get it

**Comment by jameswalston** [comment]
Imagine method 2 as being able to "extend" an existing function by having it stored in the subcommand context manager and letting the `@group(subcommands=[])` dictate the API naming. To the lib, as long as we store the appropriate name and let users access it that's what matters.

With method 1 you're forced to follow current regex and only underscore, whereas method 2 let's you focus onto the coroutine

**Comment by Toricane** [comment]
Ohh so the users have to create the subcommands in the order they inputted them in the group? Okay thanks I get it now

**Comment by Toricane** [comment]
> EDIT: maybe allow `name` as a passable field in the `@subcommand` decor to avoid the main issue with method 1

This is the decorator right now:
```py
def subcommand(
    self,
    _coro: Optional[Coroutine] = MISSING,
    *,
    name: Optional[str] = MISSING,
    description: Optional[str] = MISSING,
    options: Optional[List[Option]] = MISSING,
) -> Callable[..., Any]:
```
The `_coro` parameter basically allows you to do `@group_func.subcommand` instead of `@group_func.subcommand()`.
However, doing that means that the name needs to be inputted as a keyword only parameter.
Is that okay?

**Comment by Toricane** [comment]
Working new subcommand system has been implemented as of the latest commits, still need to implement it for extensions, though.

**Comment by Toricane** [comment]
The latest commit now addressed the extensions, please check the code if you need to see my implementation.
Also please tell me if it is overcomplicated.
Example of usage:
```py
@extension_command()
async def base(self, ctx):
    await ctx.send("base")
    return "base"  # you can return anything and get it from the argument in subcommand and group functions

@base.subcommand()
async def subcommand1(self, ctx, base_res):
    print(base_res) # <BaseResult result="base">
    await ctx.send("subcommand1")
    return "subcommand1"

@base.group()
async def group(self, ctx, base_res):
    await ctx.send("group")
    return "group"

@group.subcommand()
async def subcommand2(self, ctx, group_res):
    print(group_res) # <GroupResult result="group" parent=<BaseResult result="base">>
    await ctx.send("subcommand2")
```
